<?php

use App\Http\Controllers\studentcontroller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Middleware\Authenticate;

Route::get("tettstmail", [studentcontroller::class, "emailtest"]);

Route::get("schoolproject/index", [studentcontroller::class, "index"])->name("schoolproject.index");
Route::post("schoolproject/loginform", [studentcontroller::class, "loginform"])->name("schoolproject.loginform");
Route::get("/teachers/payment",[studentcontroller::class, 'teacherspayment'])->name("schoolproject.payment");
Route::get("schoolproject/dashboard", [studentcontroller::class, "dashboard"])->name("schoolproject.dashboard");
Route::get("schoolproject/admin-account-settings", [studentcontroller::class, "adminaccount_settings"])->name("schoolproject.adminaccount_settings");
Route::get("schoolproject/admit_form", [studentcontroller::class, "admit_form"])->name("schoolproject.admit_form");
Route::post("schoolproject/student_form", [studentcontroller::class, "student_form"])->name("schoolproject.student_form");
Route::get("schoolproject/all_student", [studentcontroller::class, "all_student"])->name("schoolproject.all_student");
Route::get("schoolproject/add_class", [studentcontroller::class, "add_class"])->name("schoolproject.add_class");
Route::get("schoolproject/add_teacher", [studentcontroller::class, "add_teacher"])->name("schoolproject.add_teacher");

Route::get("schoolproject/parentdash", [studentcontroller::class, "parentdashboard"])->name("schoolproject.parentdash");
Route::get("schoolproject/studentdashboard", [studentcontroller::class, "studentdashboard"])->name("schoolproject.studentdashboard");
Route::get("schoolproject/teacherdashboard", [studentcontroller::class, "teacherdashboard"])->name("schoolproject.teacherdashboard");

Route::post("schoolproject/addclass",[studentcontroller::class, "addclass"])->name("schoolproject.addclass");
Route::get("schoolproject/all_class",[studentcontroller::class, "all_class"])->name("schoolproject.all_class");
Route::get("schoolproject/addparents", [studentcontroller::class, "addparents"])->name ("schoolproject.addparents");
Route::get("schoolproject/allparents", [studentcontroller::class, "allparents"])->name ("schoolproject.allparents");
Route::post("schoolproject/teacherform",[studentcontroller::class, "teacherform"])->name("schoolproject.teacherform");
Route::get("schoolproject/all_teacher",[studentcontroller::class, "all_teacher"])->name("schoolproject.all_teacher");
Route::get("schoolproject/student_details/{id}", [studentcontroller::class, "student_details"])->name("schoolproject.student_details");
Route::get("schoollproject/teacher_details{id}", [studentcontroller::class, "teacher_details"])->name("schoolproject.teacher_details");
Route::delete("schoollproject/deleteclass/{id}", [studentcontroller::class, "delete_class"])->name("schoolproject.delete_class");
Route::delete("schoolproject/deleteteacher/{id}", [studentcontroller::class, "delete_teachers"])->name("schoolproject.delete_teachers");
Route::delete("schoolprojects/{id}", [studentcontroller::class, "deletestudent"])->name("schoolproject.deletestudent");
Route::get("schoolprojects/editstudent/{id}", [studentcontroller::class, "editstudent"])->name("schoolproject.editstudent");
Route::put("schoolproject/updatestudent/{id}", [studentcontroller::class, "updatestudent"])->name("schoolproject.updatestudent");
Route::get("scholproject/editteacher/{id}", [studentcontroller::class, "editteacher"])->name("schoolproject.editteacher");
Route::put("scholproject/updateteacher/{id}", [studentcontroller::class, "updateteacher"])->name("schoolproject.updateteacher");
Route::post("schoolproject/parents",[studentcontroller::class, "parents"])->name("schoolproject.parents");
Route::get('schoolproject/{class}', [studentcontroller::class, 'getStudents']);
Route::get("parentsdetails/{id}", [studentcontroller::class, "parentsdetails"])->name("schoolproject.parentsdetails");
Route::post('get-food-types', [studentcontroller::class, 'getTypes']);
Route::delete("deleteparent/{id}", [studentcontroller::class, "deleteparent"])->name("schoolproject.deleteparent");

Route::get("schoolsproject/{class}", [studentcontroller::class, "viewstudents"])->name("schoolproject.viewstudents");
Route::get("/transportation", [studentcontroller::class, "transport"])->name("schoolproject.transport");
Route::post("/transportform", [studentcontroller::class, "transportform"])->name("schoolproject.transportform");
Route::delete("/deletedriver/{id}", [studentcontroller::class, "deletedriver"])->name("schoolproject.deletedriver");
Route::get("/hostel-registration", [studentcontroller::class, "hostel"])->name("schoolproject.hostel");
Route::post("/hostelform", [studentcontroller::class, "hostelform"])->name("schoolproject.hostelform");
Route::get("/addexpense", [studentcontroller::class, "addexpense"])->name("schoolproject.addexpense");
Route::get("/allexpense", [studentcontroller::class, "allexpense"])->name("schoolproject.allexpense");
Route::get("/addbook", [studentcontroller::class, "addbook"])->name("schoolproject.addbook");
Route::get("/allbook", [studentcontroller::class, "allbook"])->name("schoolproject.allbook");
Route::get("/allsubject", [studentcontroller::class, "allsubject"])->name("schoolproject.allsubject");
Route::post("/addsubject", [studentcontroller::class, "addsubject"])->name("schoolproject.addsubject");
Route::delete("/deletesubject/{id}",[studentcontroller::class, "deletesubject"])->name("schoolproject.deletesubject");
Route::post("/bookform",[studentcontroller::class,"bookform"])->name("schoolproject.bookform");
Route::post('get-book-types', [studentcontroller::class,'getBookss']);
Route::post('getHostel', [studentcontroller::class,'getHostel']);
Route::get('studentpromotion', [studentcontroller::class,'studentpromotion'])->name("schoolproject.studentpromotion");
Route::get("/parent-expenses",[studentcontroller::class, "parentexpenses"])->name("schoolproject.parentexpenses");
Route::get("/parent-select-child", [studentcontroller::class,"parent_result"])->name("schoolproject.parent_result");
Route::get("/academic-session", [studentcontroller::class, "academic_session"])->name("schoolproject.academic_session");
Route::post("/academic", [studentcontroller::class, "academic"])->name("schoolproject.academic");
Route::delete("/delete_session/{id}", [studentcontroller::class, "delete_session"])->name("schoolproject.delete_session");
Route::delete("/deletebook/{id}", [studentcontroller::class, "deletebook"])->name("schoolproject.deletebook");
Route::get("/school-billing-package", [studentcontroller::class, "schoolfee"])->name("schoolproject.schoolfee");
Route::post("/schoolfee_form", [studentcontroller::class, "schoolfee_form"])->name("schoolproject.schoolfee_form");
Route::get("/each_class_bills", [studentcontroller::class, "each_class_bills"])->name("schoolproject.each_class_bills");
Route::post("billform", [studentcontroller::class, "billform"])->name("schoolproject.billform");
Route::delete("deletebill", [studentcontroller::class, "deletebill"])->name("schoolproject.deletebill");
Route::get("/all_school_bills", [studentcontroller::class, "all_school_bills"])->name("schoolproject.all_school_bills");
Route::delete("deletebillform{id}", [studentcontroller::class, "deletebillform"])->name("schoolproject.deletebillform");
Route::get("/mystudent{class}", [studentcontroller::class, "mystudent"])->name("schoolproject.mystudent");
Route::get("/noticeboard", [studentcontroller::class, "noticeboard"])->name("schoolproject.noticeboard");
Route::post("noticeform", [studentcontroller::class, "noticeform"])->name("schoolproject.noticeform");
Route::get("teacher_accountsettings/{id}", [studentcontroller::class, "teacher_accountsettings"])->name("schoolproject.teacher_accountsettings");
Route::put("teachereditprofile/{id}", [studentcontroller::class, "teachereditprofile"])->name("schoolproject.teachereditprofile");
Route::get("teacher-profile/{id}", [studentcontroller::class, "teacherprofile"])->name("schoolproject.teacherprofile");
Route::get("messaging/", [studentcontroller::class, "messaging"])->name("schoolproject.messaging");
Route::get("map/", [studentcontroller::class, "map"])->name("schoolproject.map");
Route::get("exam_grade/", [studentcontroller::class, "exam_grade"])->name("schoolproject.exam_grade");
Route::get("student_subjects/{classteacher}", [studentcontroller::class, "student_subjects"])->name("schoolproject.student_subjects");
Route::match(['get', 'post'], 'subjectform/', [StudentController::class, 'subjectform'])->name('schoolproject.subjectform');
Route::get("uploadresult/", [studentcontroller::class, "uploadresult"])->name("schoolproject.uploadresult");
Route::get("classSubject/", [studentcontroller::class, "classSubject"])->name("schoolproject.classSubject");
Route::post("resultform/", [studentcontroller::class, "resultform"])->name("schoolproject.resultform");
Route::put("schoolSetForm/", [studentcontroller::class, "schoolSetForm"])->name("schoolproject.schoolSetForm");
Route::get("promoteStudent/",  [studentcontroller::class, "promoteStudent"])->name("schoolproject.promoteStudent");
Route::get("makePromotion/{class}",  [studentcontroller::class, "makePromotion"])->name("schoolproject.makePromotion");
Route::put("promoteForm/", [studentcontroller::class, "promoteForm"])->name("schoolproject.promoteForm");
Route::post("existingParent", [studentcontroller::class, "existingParent"])->name("schoolproject.existingParent");
Route::get("view-expenses/", [studentcontroller::class, "viewexpenses"])->name("schoolproject.viewexpenses");
Route::post("viewexpenseform", [studentcontroller::class, "viewexpenseform"])->name("schoolproject.viewexpenseform");
Route::get("parentprofile/", [studentcontroller::class, "parentprofile"])->name("schoolproject.parentprofile");
Route::get("school_setting/", [studentcontroller::class,"school_setting"])->name("schoolproject.school_setting");
Route::get("selectstudent/{id}", [studentcontroller::class, "selectstudent"])->name("schoolproject.selectstudent");
Route::get("addresult/{id}", [studentcontroller::class, "addresult"])->name("schoolproject.addresult");
Route::get("parent_accountsettings/{id}", [studentcontroller::class, "parent_accountsettings"])->name("schoolproject.parent_accountsettings");
Route::put("parenteditprofile/{id}", [studentcontroller::class, "parenteditprofile"])->name("schoolproject.parenteditprofile");
Route::get("parentviewresult/", [studentcontroller::class, "parentviewresult"])->name("schoolproject.parentviewresult");
Route::post("checkresultform", [studentcontroller::class, "checkresultform"])->name("schoolproject.checkresultform");
Route::post("AdminsendMessage", [studentcontroller::class, "AdminsendMessage"])->name("schoolproject.AdminsendMessage");
Route::post("paymentform", [studentcontroller::class, "paymentform"])->name("schoolproject.paymentform");
Route::get("sendproof/{id}", [studentcontroller::class, "sendproof"])->name("schoolproject.sendproof");
Route::post("sendproofform/", [studentcontroller::class, "sendproofform"])->name("schoolproject.sendproofform");
Route::get("approvedpayment", [studentcontroller::class,"approvedpayment"])->name("schoolproject.approvedpayment");
Route::get("pendingpayment", [studentcontroller::class, "pendingpayment"])->name("schoolproject.pendingpayment");
Route::put("declineform", [studentcontroller::class, "declineform"])->name("schoolproject.declineform");
Route::get("approve/{id}", [studentcontroller::class, "approve"])->name("schoolproject.approve");
Route::put("approveform/", [studentcontroller::class, "approveform"])->name("schoolproject.approveform"); 
Route::get("updateterm", [studentcontroller::class, "updateterm"])->name("schoolproject.updateterm");
Route::put("updatetermform", [studentcontroller::class, "updatetermform"])->name("schoolproject.updatetermform");
Route::get("approveresult", [studentcontroller::class, "approveresult"])->name("schoolproject.approveresult");
Route::post("approveresultform", [studentcontroller::class, "approveresultform"])->name("schoolproject.approveresultform");
Route::get("selectstudentresult", [studentcontroller::class, "selectstudentresult"])->name("schoolproject.selectstudentresult");
Route::get("finalapproveresult/", [studentcontroller::class, "finalapproveresult"])->name("schoolproject.finalapproveresult");
Route::post("continueresultform/", [studentcontroller::class, "continueresultform"])->name("schoolproject.continueresultform");
Route::get("parentpaymentstatus/", [studentcontroller::class, "parentpaymentstatus"])->name("schoolproject.parentpaymentstatus");
Route::get("select-child", [studentcontroller::class, "selectChildPayment"])->name("schoolproject.selectChildPayment");
Route::post("payexpenses", [studentcontroller::class, "payexpenses"])->name("schoolproject.payexpenses");
Route::get("makePayment/", [studentcontroller::class, "makePayment"])->name("schoolproject.makePayment");
Route::get("all-fees", [studentcontroller::class, "all_fees"])->name("schoolproject.all_fees");
Route::get("addpayment", [studentcontroller::class, "addpayment"])->name("schoolproject.addpayment");
Route::put("updateprincipalreport", [studentcontroller::class, "updateprincipalreport"])->name("schoolproject.updateprincipalreport");
Route::get("sendresult", [studentcontroller::class, "sendresult"])->name("schoolproject.sendresult");
Route::post("sendresultform", [studentcontroller::class, "sendresultform"])->name("schoolproject.sendresultform");
Route::get("teachersendresult", [studentcontroller::class, "teachersendresult"])->name("schoolproject.teachersendresult");
Route::post("teachersendresultform/", [studentcontroller::class, "teachersendresultform"])->name("schoolproject.teachersendresultform");

Route::get("forgot-password/", [studentcontroller::class, "forgotpassword"])->name("schoolproject.forgotpassword");
Route::post("forgotform/", [studentcontroller::class, "forgotform"])->name("schoolproject.forgotform");
Route::get("change-password/", [studentcontroller::class, "changepassword"])->name("schoolproject.changepassword");
Route::put("passwordform", [studentcontroller::class, "passwordform"])->name("schoolproject.passwordform");

